Repository barrel/shopify-vite, pull requests merged in 2022-08, with the labels that each got.

#5 Link to example using absolute url
  packages/vite-plugin-shopify/README.md
Labels: documentation

#4 Add style tag for style.css
  packages/vite-plugin-shopify/src/html.ts
  themes/vite-shopify-example/assets/counter.d37853c9.js
  themes/vite-shopify-example/assets/counter.d37853c9.js.map
  themes/vite-shopify-example/assets/manifest.json
  themes/vite-shopify-example/assets/theme.0745d26d.js
  themes/vite-shopify-example/assets/theme.0745d26d.js.map
  themes/vite-shopify-example/snippets/vite-client.liquid
  themes/vite-shopify-example/snippets/vite-tag.liquid
Labels: bug

#6 Enable code-splitting per module
  .changeset/grumpy-carrots-walk.md
  .changeset/wet-elephants-press.md
  .vscode/settings.json
  packages/vite-plugin-shopify-modules/README.md
  packages/vite-plugin-shopify-modules/package.json
  packages/vite-plugin-shopify-modules/src/index.ts
  packages/vite-plugin-shopify/README.md
  packages/vite-plugin-shopify/src/config.ts
  packages/vite-plugin-shopify/src/html.ts
  packages/vite-plugin-shopify/src/options.ts
  pnpm-lock.yaml
  themes/seed-theme/frontend/entrypoints/theme.js
  themes/seed-theme/frontend/scripts/dynamic-section-element.js
  themes/seed-theme/layout/theme.liquid
  themes/seed-theme/modules/picture/picture.js
  themes/seed-theme/modules/picture/picture.snippet.liquid
  themes/seed-theme/modules/radio-input/radio-input.snippet.liquid
  themes/seed-theme/modules/slider-dots/slider-dots.js
  themes/seed-theme/modules/slider-dots/slider-dots.snippet.liquid
  themes/seed-theme/modules/video/video.snippet.liquid
  themes/seed-theme/sections/account-addresses.liquid
  themes/seed-theme/sections/account-form.liquid
  themes/seed-theme/sections/account-orders.liquid
  themes/seed-theme/sections/cart.liquid
  themes/seed-theme/sections/collection-product-grid.liquid
  themes/seed-theme/sections/hero-slider.liquid
  themes/seed-theme/sections/product-grid-toggle.liquid
  themes/seed-theme/sections/product-main.liquid
  themes/seed-theme/sections/recently-viewed-products.liquid
  themes/seed-theme/sections/recommended-products.liquid
  themes/seed-theme/sections/site-header.liquid
  themes/seed-theme/sections/style-guide.liquid
  themes/seed-theme/snippets/account-address-form.liquid
  themes/seed-theme/snippets/account-address-summary.liquid
  themes/seed-theme/snippets/announcement-bar.liquid
  themes/seed-theme/snippets/background-video.liquid
  themes/seed-theme/snippets/cart-item.liquid
  themes/seed-theme/snippets/picture.liquid
  themes/seed-theme/snippets/product-form.liquid
  themes/seed-theme/snippets/product-gallery.liquid
  themes/seed-theme/snippets/quantity-input.liquid
  themes/seed-theme/snippets/radio-input.liquid
  themes/seed-theme/snippets/slider-dots.liquid
  themes/seed-theme/snippets/video.liquid
  themes/seed-theme/tailwind.config.js
  themes/seed-theme/templates/collection.listing.json
  themes/seed-theme/templates/page.collection-storytelling.json
  themes/seed-theme/vite.config.js
Labels: enhancement
